model: resnet50
checkpoint: "output/train/LOGICSEG_BCE/model_best.pth.tar"
data_dir: "data/small-collomboles/dataset/test"
num_classes: 136

results_dir: "output/test/logicseg_bce"
results_file: "test_logicseg_bce"

conf_matrix: True

csv_tree: "data/small-collomboles/hierarchy.csv"
logicseg: True
class_map: "classmap/classmap.pkl"

device: "cpu"